all:
	gcc -Wall -D_GNU_SOURCE main.c caller.c callee.c empty_msg.h ../../../../common/ipc.c -I../../../../include -I../../include -o empty_msg -pthread 

all2:
	gcc -Wall -D_GNU_SOURCE main2.c ../../../../common/ipc.c -I../../../../include -I../../include -o empty_msg2 -pthread 
