
all:
	@gcc \
		-I/home/ed/Desktop/fast-ipc-module \
		-I/home/ed/Desktop/fast-ipc-module/src/include \
		-I/home/ed/Desktop/fast-ipc-module/src/platform/userland/include \
		-c ../../common/ipc.c
	@ar rcs libfipc.a ipc.o