all:
#	g++ -O2 -g -o master master.cpp
#	g++ -O2 -g -o slave slave.cpp
#	gcc  -g -O2 -o master mymaster_cachepoll.c
#	gcc  -g -O2 -o slave myslave_cachepoll.c
	gcc  -g -O2 -o master master_fromkland.c
	gcc  -g -O2 -o slave slave_fromkland.c
#	gcc  -g -O2 -Wall -Wextra -Werror -o master mymaster_nextcachepoll.c
#	gcc --std=gnu99 -g -O2 -o slave myslave_nextcachepoll.c
#	gcc  -g -O2 -Wall -Wextra -Werror -o master mymaster_cachepoll_ONEWAY.c
#	gcc -g -g -O2 -o slave myslave_cachepoll_ONEWAY.c
